### ISSUE TITLE
添加MenuStrip控件存在问题

### ISSUE THREAD

**Issue by dongnanyanhai** [SmallAnts/FormDesigner.Demo#10]
在设计器上添加MenuStrip控件和子菜单时，部分情况下，会出现“System.NullReferenceException:未将对象引用设置到对象的实例”，错误定位Application.Run(new MainForm());这一行代码，无法确定具体错误原因。

导出xml时，子菜单的属性信息会丢失，只导出下面这样的xml代码：
<Item0 mode="reference">ToolStripMenuItem1</Item0>

另外System.Design相关的控件会被导出（例如System.Windows.Forms.Design.DesignerToolStripControlHost），看xml内容，应该是设计时存在的，这些能否不要导出？

**Comment by SmallAnts** [comment]
问题已修复，并在 NUGET 上推送了 Smart.FormDesigner.1.4.3 版本。

**Comment by dongnanyanhai** [comment]
辛苦了！！！

**Comment by dongnanyanhai** [comment]
问题解决了，非感谢！
