### ISSUE TITLE
ListView控件产生的XML代码问题

### ISSUE THREAD

**Issue by dongnanyanhai** [SmallAnts/FormDesigner.Demo#11]
添加Column后，System.Windows.Forms.ColumnHeader对应的xml数据缺少属性信息。

添加items后，System.Windows.Forms.ListViewItem对应的xml有有两个<Param>节点；第一个节点是具体的文本，第二个<Param>-1</Param>有点不确定是什么用途。

**Comment by SmallAnts** [comment]
源码已经提交至 https://github.com/SmallAnts/FormDesigner ，可以自己取代代码修改。

**Comment by dongnanyanhai** [comment]
> 源码已经提交至 https://github.com/SmallAnts/FormDesigner ，可以自己取代代码修改。

感谢啊！！！

差点就无法继续了！！！

**Comment by dongnanyanhai** [comment]
> 源码已经提交至 https://github.com/SmallAnts/FormDesigner ，可以自己取代代码修改。

非常感谢！！！
