### ISSUE TITLE
更新到1.4 后，ShowEventTab不起作用

### ISSUE THREAD

**Issue by dongnanyanhai** [SmallAnts/FormDesigner.Demo#9]
Smart.FormDesigner更新到1.4后，发现没有事件列表了。

**Comment by dongnanyanhai** [comment]
具体情况是：未改动FormDesigner.Demo的代码，更新到Smart.FormDesigner 1.4后，右侧属性窗口没有“事件”按钮。

**Comment by SmallAnts** [comment]
已经推送了 1.4.1 版本修复此问题。

**Comment by dongnanyanhai** [comment]
> 已经推送了 1.4.1 版本修复此问题。

感谢修复，辛苦了！

**Comment by SmallAnts** [comment]
v1.4.1 还是有些bug，可以更新到 v1.4.2
